version: "3.9"

services:
  flask-app:
    image: ghcr.io/${GITHUB_REPOSITORY}/flask-app:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5000:80"
    environment:
      - PYTHONUNBUFFERED=1
